name: Daily API test

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: true
        default: 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
         newman run FLOW_GH.postman_collection.json\
         --export-collection-variables vars_output.json

      - name: Extract Email from Collection Vars
        run: |
          # The structure for collection variables is slightly different in the JSON export
          EMAIL=$(jq -r '.values[] | select(.key=="currentEmail") | .value' vars_output.json)
          echo "USER_EMAIL=$EMAIL" >> $GITHUB_ENV
          echo "Captured Email: $EMAIL"
