name: Daily API test

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: true
        default: 'main'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run your_collection_file.json
